### PR TITLE
Windows-CLI fix the 'input line is too long' error

### PR DESCRIPTION
**Pull request by bakejeyner**
### Description of the Change
Fix the windows 'input line is too long' CLI issue.

### Checklist:
- [ ] Unit Tests Added/Modified

### CODE REVIEW

**Comment by bakejeyner** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by bakejeyner** [comment]
build now
(if this doesn't work, I'm going to get blen to get Jenkins in line)

**Comment by blen-desta** [comment]
@bakejeyner it's already building

**Pull request merged**
